apiVersion: v1
kind: Service
metadata:
  labels: null
  name: monitoring-influxdb
  namespace: default
spec:
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  - name: api
    port: 8086
    targetPort: 8086
  clusterIP: 10.0.0.15
  selector:
    name: influxGrafana
