apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: heapster
    name: heapster
    version: v6
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v6
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v6
    spec:
      containers:
      - name: heapster
        image: 10.1.23.1:5000/heapster-snap:1
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes.snap:http://10.1.23.1:8080
        - --sink=influxdb:http://10.2.50.51:8086
